In [41]:
import pandas as pd
import ast


df_original = pd.read_csv('data/original.csv')
df_additional = pd.read_csv('data/movies_with_missing_keywords.csv', on_bad_lines='skip')

In [42]:
df_original['Keyword'].unique()

with open('data/keywords.txt', 'r', encoding='utf-8') as file:
    valid_keywords = set(file.read().splitlines())  # txt 파일에서 키워드 읽어서 set으로 저장

# 'Keyword' 컬럼 값 중 유효하지 않은 키워드 필터링
invalid_rows = df_original[~df_original['Keyword'].isin(valid_keywords)]

# 유효하지 않은 행의 개수
invalid_count = len(invalid_rows)

In [43]:
invalid_count

0

In [20]:
df_original = df_original[df_original['Keyword'].isin(valid_keywords)]

In [44]:

# 'Keyword' 컬럼 값 중 유효하지 않은 키워드 필터링
invalid_rows = df_additional[~df_additional['Keyword'].isin(valid_keywords)]

# 유효하지 않은 행의 개수
invalid_count = len(invalid_rows)
invalid_count

4

In [45]:
df_additional = df_additional[df_additional['Keyword'].isin(valid_keywords)]

In [49]:
df_original = df_original.drop(columns=['Unnamed: 0'])

In [50]:
df_original

                     Keyword                                    Title                                                                                                                                                                                                                                   Description  Rating
0          alternate history                               Eraserhead                                                                                                      Henry Spencer tries to survive his industrial environment, his angry girlfriend, and the unbearable screams of his newborn mutant child.     7.3
1          alternate history         Once Upon a Time... in Hollywood  As Hollywood's Golden Age is winding down during the summer of 1969, television actor Rick Dalton and his stunt double Cliff Booth endeavor to achieve lasting success in Hollywood while meeting several colorful characters along the way.     7.6
2          alternate history                               Bridgerton                                                                                                                                    The eight close-knit siblings of the Bridgerton family look for love and happiness in London high society.     7.4
3          alternate history                          For All Mankind                                                                 In an alternative version of 1969, the Soviet Union beats the United States to the Moon, and the space race continues on for decades with still grander challenges and goals.     8.1
4          alternate history                     Inglourious Basterds                                                              In Nazi-occupied France during World War II, a plan to assassinate Nazi leaders by a group of Jewish U.S. soldiers coincides with a theatre owner's vengeful plans for the same.     8.4
...                      ...                                      ...                                                                                                                                                                                                                                           ...     ...
309531  voice over narration                             The Dreamers                                                                               A young American studying in Paris in 1968 strikes up a friendship with a French brother and sister. Set against the background of the '68 Paris student riots.     7.1
309532  voice over narration  Dungeons & Dragons: Honor Among Thieves                                                                 A charming thief and a band of unlikely adventurers embark on an epic quest to retrieve a lost relic, but things go dangerously awry when they run afoul of the wrong people.     7.2
309533  voice over narration                                The Mummy               At an archaeological dig in the ancient city of Hamunaptra, an American serving in the French Foreign Legion accidentally awakens a mummy who begins to wreak havoc as he searches for the reincarnation of his long-lost love.     7.1
309534  voice over narration                 Avatar: The Way of Water      Jake Sully lives with his newfound family formed on the extrasolar moon Pandora. Once a familiar threat returns to finish what was previously started, Jake must work with Neytiri and the army of the Na'vi race to protect their home.     7.5
309535  voice over narration                             Transformers                                                                       An ancient struggle between two Cybertronian races, the heroic Autobots and the evil Decepticons, comes to Earth, with a clue to the ultimate power held by a teenager.     7.1

[309536 rows x 4 columns]

In [51]:
df_additional

                       Keyword                             Title                                                                                                                                                                                                                                   Description  Rating
0      character name in title                        Eraserhead                                                                                                      Henry Spencer tries to survive his industrial environment, his angry girlfriend, and the unbearable screams of his newborn mutant child.     7.3
1      character name in title  Once Upon a Time... in Hollywood  As Hollywood's Golden Age is winding down during the summer of 1969, television actor Rick Dalton and his stunt double Cliff Booth endeavor to achieve lasting success in Hollywood while meeting several colorful characters along the way.     7.6
2      character name in title                        Bridgerton                                                                                                                                    The eight close-knit siblings of the Bridgerton family look for love and happiness in London high society.     7.4
3      character name in title              Inglourious Basterds                                                              In Nazi-occupied France during World War II, a plan to assassinate Nazi leaders by a group of Jewish U.S. soldiers coincides with a theatre owner's vengeful plans for the same.     8.4
4      character name in title                   For All Mankind                                                                 In an alternative version of 1969, the Soviet Union beats the United States to the Moon, and the space race continues on for decades with still grander challenges and goals.     8.1
...                        ...                               ...                                                                                                                                                                                                                                           ...     ...
19892                   murder             This Is Going to Hurt                                                                     Heartbroken Adam does his first shift at a posh private hospital and finds that it's not all it's cracked up to be. Shruti has a challenging night shift on the NHS Ward.     9.1
19893                   murder             This Is Going to Hurt                                                                  A grieving Adam faces a tribunal over his malpractice, and is no longer sure if he can go on in medicine. Reconnecting with Harry, he tries to decide where his future lies.     8.4
19894                   murder                  The Innocent Man                                                                                                        Focuses on two murders that shook the small town of Ada, Oklahoma, in the 1980s - and the controversial chain of events that followed.     7.3
19895                   murder              Detective Montalbano              Livia sends Montalbano to a seamstress to have a new suit made for an upcoming event. Montalbano likes the seamstress but before he can pick up his new suit, she is murdered and there are very few clues as to why or by whom.     6.7
19896                   murder              Detective Montalbano  Montalbano investigates the murder of an elderly man in his home and the discovery of a hidden diary from 1943, theorizing they may be connected somehow. Unrelated false clues abound, which seems to be a common theme in recent episodes.     7.8

[19893 rows x 4 columns]

In [52]:
df = pd.concat([df_original, df_additional])

df

                 Keyword                             Title                                                                                                                                                                                                                                   Description  Rating
0      alternate history                        Eraserhead                                                                                                      Henry Spencer tries to survive his industrial environment, his angry girlfriend, and the unbearable screams of his newborn mutant child.     7.3
1      alternate history  Once Upon a Time... in Hollywood  As Hollywood's Golden Age is winding down during the summer of 1969, television actor Rick Dalton and his stunt double Cliff Booth endeavor to achieve lasting success in Hollywood while meeting several colorful characters along the way.     7.6
2      alternate history                        Bridgerton                                                                                                                                    The eight close-knit siblings of the Bridgerton family look for love and happiness in London high society.     7.4
3      alternate history                   For All Mankind                                                                 In an alternative version of 1969, the Soviet Union beats the United States to the Moon, and the space race continues on for decades with still grander challenges and goals.     8.1
4      alternate history              Inglourious Basterds                                                              In Nazi-occupied France during World War II, a plan to assassinate Nazi leaders by a group of Jewish U.S. soldiers coincides with a theatre owner's vengeful plans for the same.     8.4
...                  ...                               ...                                                                                                                                                                                                                                           ...     ...
19892             murder             This Is Going to Hurt                                                                     Heartbroken Adam does his first shift at a posh private hospital and finds that it's not all it's cracked up to be. Shruti has a challenging night shift on the NHS Ward.     9.1
19893             murder             This Is Going to Hurt                                                                  A grieving Adam faces a tribunal over his malpractice, and is no longer sure if he can go on in medicine. Reconnecting with Harry, he tries to decide where his future lies.     8.4
19894             murder                  The Innocent Man                                                                                                        Focuses on two murders that shook the small town of Ada, Oklahoma, in the 1980s - and the controversial chain of events that followed.     7.3
19895             murder              Detective Montalbano              Livia sends Montalbano to a seamstress to have a new suit made for an upcoming event. Montalbano likes the seamstress but before he can pick up his new suit, she is murdered and there are very few clues as to why or by whom.     6.7
19896             murder              Detective Montalbano  Montalbano investigates the murder of an elderly man in his home and the discovery of a hidden diary from 1943, theorizing they may be connected somehow. Unrelated false clues abound, which seems to be a common theme in recent episodes.     7.8

[329429 rows x 4 columns]

In [53]:
pd.set_option("display.max_columns", None)  # 모든 열 표시
pd.set_option("display.max_colwidth", None)  # 열 내용 길이 제한 해제
pd.set_option("display.expand_frame_repr", False)  # 가로로 출력

# Keyword별 행 개수 계산
keyword_counts = df['Keyword'].value_counts()

# 결과 출력
print("Keyword Counts:")
print(keyword_counts)

Keyword Counts:
Keyword
kidnapping                   10669
title spoken by character     9519
superhero                     8125
investigation                 7501
supernatural power            7155
                             ...
french new wave                 95
deus ex machina                 77
tech noir                       73
neorealism                      35
no background score              5
Name: count, Length: 148, dtype: int64

In [56]:
df_keywords = set(df['Keyword'].unique())

# keywords.txt에만 있는 키워드 확인 -> 없음
missing_keywords = valid_keywords - df_keywords

len(missing_keywords)

0

In [57]:
df.to_csv('data/original.csv', index=False)

In [58]:
df_final = pd.read_csv('data/refined.csv')
df_final

                                   Title                                                                                                                                                                                                                                   Description                                                                                                                                                                                                                                                                                                                          Keywords  Rating
0                             Eraserhead                                                                                                      Henry Spencer tries to survive his industrial environment, his angry girlfriend, and the unbearable screams of his newborn mutant child.                                                                                                                           ["no opening credits", "character name in title", "cult film", "husband wife relationship", "dream sequence", "alternate history", "experimental film", "avant garde", "parenthood", "surprise ending"]     7.3
1       Once Upon a Time... in Hollywood  As Hollywood's Golden Age is winding down during the summer of 1969, television actor Rick Dalton and his stunt double Cliff Booth endeavor to achieve lasting success in Hollywood while meeting several colorful characters along the way.  ["fantasy sequence", "wilhelm scream", "surprise ending", "voice over narration", "character name in title", "action hero", "nonlinear timeline", "multiple storylines", "based on novel", "double cross", "cult", "betrayal", "kung fu", "alternate history", "no title at beginning", "rescue", "ensemble cast", "conspiracy"]     7.6
2                             Bridgerton                                                                                                                                    The eight close-knit siblings of the Bridgerton family look for love and happiness in London high society.                                                                                                                                                                                                                                                       ["character name in title", "murder", "based on book", "alternate history"]     7.4
3                        For All Mankind                                                                 In an alternative version of 1969, the Soviet Union beats the United States to the Moon, and the space race continues on for decades with still grander challenges and goals.                                                                                                                                                                                                                                                                                  ["character name in title", "alternate history"]     8.1
4                   Inglourious Basterds                                                              In Nazi-occupied France during World War II, a plan to assassinate Nazi leaders by a group of Jewish U.S. soldiers coincides with a theatre owner's vengeful plans for the same.          ["director cameo", "good versus evil", "wilhelm scream", "multiple perspectives", "shootout", "voice over narration", "character name in title", "father daughter relationship", "nonlinear timeline", "self sacrifice", "alternate history", "cult film", "betrayal", "american abroad", "psychopath", "investigation"]     8.4
...                                  ...                                                                                                                                                                                                                                           ...                                                                                                                                                                                                                                                                                                                               ...     ...
152451                     Gorilla DaDan                                                                                                                                 A psychic middle schooler who want's to live a normal live growing his power, but keeps running into trouble.                                                                                                                                                                                                                                                                                                                        ["murder"]     8.1
152452     Ford: The Man and the Machine                                                                                                                                                         The life of Henry Ford, and how he changed America while keeping his family together.                                                                                                                                                                                                                                                                                                                        ["murder"]     6.5
152453                 The Devil's Feast            When the beautiful Kumiko joins the editorial desk at a small local newspaper, the most deeply kept secrets of the rich and powerful leader of a religious cult suddenly begin finding their way into print in blistering exposes.                                                                                                                                                                                                                                                                                                                        ["murder"]     4.9
152454                   Tell Me My Name                             Based on the book by Mary Carter"Tell Me My Name" is about a girl's visit to the woman who gave her up for adoption 19 years earlier. The adoption was a secret which now threatens to destroy the entire family.                                                                                                                                                                                                                                                                                                                        ["murder"]     4.6
152455                      I, Crocodile                                  An Egyptian crocodile lives happily in his new home in Paris, until a chef tries to turn him into dinner. The crocodile escapes through the sewers and lives to tell about his newest menu delight - people!                                                                                                                                                                                                                                                                                                                        ["murder"]     6.6

[152456 rows x 4 columns]

In [59]:
import json
# Keywords 컬럼을 JSON 리스트로 변환
df_final["Keywords"] = df_final["Keywords"].apply(json.loads)


df_final["Keyword_Count"] = df_final["Keywords"].apply(len)
df_final

                                   Title                                                                                                                                                                                                                                   Description                                                                                                                                                                                                                                                                                      Keywords  Rating  Keyword_Count
0                             Eraserhead                                                                                                      Henry Spencer tries to survive his industrial environment, his angry girlfriend, and the unbearable screams of his newborn mutant child.                                                                                                           [no opening credits, character name in title, cult film, husband wife relationship, dream sequence, alternate history, experimental film, avant garde, parenthood, surprise ending]     7.3             10
1       Once Upon a Time... in Hollywood  As Hollywood's Golden Age is winding down during the summer of 1969, television actor Rick Dalton and his stunt double Cliff Booth endeavor to achieve lasting success in Hollywood while meeting several colorful characters along the way.  [fantasy sequence, wilhelm scream, surprise ending, voice over narration, character name in title, action hero, nonlinear timeline, multiple storylines, based on novel, double cross, cult, betrayal, kung fu, alternate history, no title at beginning, rescue, ensemble cast, conspiracy]     7.6             18
2                             Bridgerton                                                                                                                                    The eight close-knit siblings of the Bridgerton family look for love and happiness in London high society.                                                                                                                                                                                                                           [character name in title, murder, based on book, alternate history]     7.4              4
3                        For All Mankind                                                                 In an alternative version of 1969, the Soviet Union beats the United States to the Moon, and the space race continues on for decades with still grander challenges and goals.                                                                                                                                                                                                                                                  [character name in title, alternate history]     8.1              2
4                   Inglourious Basterds                                                              In Nazi-occupied France during World War II, a plan to assassinate Nazi leaders by a group of Jewish U.S. soldiers coincides with a theatre owner's vengeful plans for the same.      [director cameo, good versus evil, wilhelm scream, multiple perspectives, shootout, voice over narration, character name in title, father daughter relationship, nonlinear timeline, self sacrifice, alternate history, cult film, betrayal, american abroad, psychopath, investigation]     8.4             16
...                                  ...                                                                                                                                                                                                                                           ...                                                                                                                                                                                                                                                                                           ...     ...            ...
152451                     Gorilla DaDan                                                                                                                                 A psychic middle schooler who want's to live a normal live growing his power, but keeps running into trouble.                                                                                                                                                                                                                                                                                      [murder]     8.1              1
152452     Ford: The Man and the Machine                                                                                                                                                         The life of Henry Ford, and how he changed America while keeping his family together.                                                                                                                                                                                                                                                                                      [murder]     6.5              1
152453                 The Devil's Feast            When the beautiful Kumiko joins the editorial desk at a small local newspaper, the most deeply kept secrets of the rich and powerful leader of a religious cult suddenly begin finding their way into print in blistering exposes.                                                                                                                                                                                                                                                                                      [murder]     4.9              1
152454                   Tell Me My Name                             Based on the book by Mary Carter"Tell Me My Name" is about a girl's visit to the woman who gave her up for adoption 19 years earlier. The adoption was a secret which now threatens to destroy the entire family.                                                                                                                                                                                                                                                                                      [murder]     4.6              1
152455                      I, Crocodile                                  An Egyptian crocodile lives happily in his new home in Paris, until a chef tries to turn him into dinner. The crocodile escapes through the sewers and lives to tell about his newest menu delight - people!                                                                                                                                                                                                                                                                                      [murder]     6.6              1

[152456 rows x 5 columns]

In [60]:
df_final["Text"] = df_final["Title"] + " " + df_final["Description"]

In [66]:
from sklearn.preprocessing import MultiLabelBinarizer

# Multi-label binarizer로 Keywords를 One-hot Encoding
mlb = MultiLabelBinarizer()
y = mlb.fit_transform(df_final["Keywords"])
texts = [title + " " + desc for title, desc in zip(df_final["Title"], df_final["Description"])]


# 출력 라벨 확인
print(f"Number of keywords: {len(mlb.classes_)}")
print(f"Encoded Labels Shape: {y.shape}")

print(f"Number of Texts: {len(texts)}")

Number of keywords: 148
Encoded Labels Shape: (152456, 148)
Number of Texts: 152456

In [62]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification

# 모델과 토크나이저 로드
model_name = "bert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=len(mlb.classes_))

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [ ]:
import torch
from torch.utils.data import Dataset, DataLoader

class KeywordDataset(Dataset):
    def __init__(self, texts, labels, tokenizer, max_length=512):
        self.texts = texts
        self.labels = labels
        self.tokenizer = tokenizer
        self.max_length = max_length

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        text = self.texts[idx]
        label = self.labels[idx]
        encoding = self.tokenizer(
            text,
            truncation=True,
            padding="max_length",
            max_length=self.max_length,
            return_tensors="pt"
        )
        return {
            "input_ids": encoding["input_ids"].squeeze(0),
            "attention_mask": encoding["attention_mask"].squeeze(0),
            "labels": torch.tensor(label, dtype=torch.float)
        }

In [ ]:
from sklearn.model_selection import train_test_split
import numpy as np
from tqdm import tqdm  



# 데이터 분할
X_train, X_val, y_train, y_val = train_test_split(texts, y, test_size=0.2, random_state=42)


# 데이터셋 및 DataLoader 생성
train_dataset = KeywordDataset(X_train, y_train, tokenizer)
val_dataset = KeywordDataset(X_val, y_val, tokenizer)

train_loader = DataLoader(train_dataset, batch_size=8, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=8, shuffle=False)

# 라벨 빈도 계산 및 가중치 생성
label_counts = y.sum(axis=0)
class_weights = 1.0 / label_counts
class_weights_tensor = torch.tensor(class_weights, dtype=torch.float).to("cuda")

# 손실 함수
loss_fn = torch.nn.BCEWithLogitsLoss(pos_weight=class_weights_tensor)

# 옵티마이저 및 학습 설정
optimizer = torch.optim.AdamW(model.parameters(), lr=5e-5)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)


# 학습 루프
def train_epoch(model, dataloader, optimizer, loss_fn, device):
    model.train()
    total_loss = 0

    # tqdm으로 데이터로더 래핑
    for batch in tqdm(dataloader, desc="Training", leave=False):
        optimizer.zero_grad()
        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        labels = batch["labels"].to(device)

        outputs = model(input_ids=input_ids, attention_mask=attention_mask)
        logits = outputs.logits
        loss = loss_fn(logits, labels)
        loss.backward()
        optimizer.step()

        total_loss += loss.item()
    return total_loss / len(dataloader)

# 평가 루프
def eval_epoch(model, dataloader, loss_fn, device):
    model.eval()
    total_loss = 0
    all_preds = []
    all_labels = []

    # tqdm으로 데이터로더 래핑
    for batch in tqdm(dataloader, desc="Evaluating", leave=False):
        with torch.no_grad():
            input_ids = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)
            labels = batch["labels"].to(device)

            outputs = model(input_ids=input_ids, attention_mask=attention_mask)
            logits = outputs.logits
            loss = loss_fn(logits, labels)
            total_loss += loss.item()

            preds = torch.sigmoid(logits) > 0.5
            all_preds.append(preds.cpu().numpy())
            all_labels.append(labels.cpu().numpy())

    return total_loss / len(dataloader), np.vstack(all_preds), np.vstack(all_labels)

# 학습 및 평가
epochs = 3
for epoch in range(epochs):
    print(f"Epoch {epoch + 1}/{epochs}")

    train_loss = train_epoch(model, train_loader, optimizer, loss_fn, device)
    val_loss, val_preds, val_labels = eval_epoch(model, val_loader, loss_fn, device)

    print(f"Train Loss: {train_loss:.4f}")
    print(f"Validation Loss: {val_loss:.4f}")

Epoch 1/3

Training:   5%|▌         | 831/15246 [04:37<1:21:31,  2.95it/s]

In [ ]:
def predict(texts):
    model.eval()
    encodings = tokenizer(
        texts,
        truncation=True,
        padding="max_length",
        max_length=512,
        return_tensors="pt"
    )
    with torch.no_grad():
        outputs = model(
            input_ids=encodings["input_ids"],
            attention_mask=encodings["attention_mask"]
        )
    logits = outputs.logits
    probs = torch.sigmoid(logits)  # Multi-label Classification에서는 sigmoid 사용
    predictions = (probs > 0.5).int()  # 0.5 기준으로 라벨 선택
    return predictions

# 예측 예시
sample_texts = ["A superhero saves the city", "A thrilling investigation"]
predicted_labels = predict(sample_texts)

# 예측된 키워드 디코딩
predicted_keywords = mlb.inverse_transform(predicted_labels.numpy())
print(predicted_keywords)

In [ ]:
label_counts = y.sum(axis=0)
class_weights = 1.0 / label_counts

loss_function = torch.nn.BCEWithLogitsLoss(weight=torch.tensor(class_weights))